name: 'Trigger Integration tests'
on:
  push:
    branches:
      - main

jobs:
  trigger-integration-tests:
    name: Trigger Integration tests
    runs-on: ubuntu-latest
    env:
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: npm install and build
        id: action-npm-build
        run: |
            npm install
            npm run build
      - name: Setup slotalk
        uses: ./
        with:
          version: 'latest'
      - name: Validate
        run: |
          slotalk version
