name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    env:
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v3
      - run: |
           echo $PR_BASE_REF
           if [[ $PR_BASE_REF != releases/* ]]; then
             npm install
             npm run build
           fi
      - name: Setup slotalk
        uses: ./
        with:
          version: 'latest'
      - name: Validate Lastest
        run: |
          slotalk version
      - name: Setup slotalk
        uses: ./
      - name: Validate No Version Input
        run: |
          slotalk version
      - name: Setup slotalk
        uses: ./
        with:
          version: '0.1.0-alpha.1'
      - name: Validate With targeted version
        run: |
          slotalk version
